import time
import base64
print("This script will reset your username & password")
time.sleep(3)
username1= input("Please type your email: ")
password1 = input("Please type a password: ")
print("Your email & password has passed the verification!")
time.sleep(1)
print("Saving and encrypting password...")
time.sleep(2)
fuser=open("user_log.txt",'wb')
fpass=open("pass_log.txt",'wb')
username= base64.b64encode(username1.encode("utf-8"))
password = base64.b64encode(password1.encode("utf-8"))
fuser.write(username)
fpass.write(password)
print("showing username & password soon")
time.sleep(2)
finaluser=base64.b64decode(username).decode("utf-8")
finalpass=base64.b64decode(password).decode("utf-8")
print(finaluser)
print(finalpass)
fuser.close()
fpass.close()
print("Done!")